<a href="https://colab.research.google.com/github/Faizan011-LTIM/Pandas-Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas
Pandas is a python library used for data analysis and manupulation.
It provide tool for handling structured data such as tables with powerful features to clean,filter and analyze data efficiently.

In [ ]:
import pandas as pd                  # Import PANDAS Library
df = pd.read_excel("Sales.xlsx")     # Read the excel file
print(df)                            # Display the data in tabular form

    OrderID  OrderDate   Region  Manager                 Man_Email_ID  \
0         1 2018-01-06     East   Martha  alam.mdimtiyaz085@gmail.com
1         2 2018-01-23  Central  Hermann        ishtiaz2023@gmail.com
2         3 2018-02-09  Central  Hermann        ishtiaz2023@gmail.com
3         4 2018-02-26  Central  Timothy           ncec1320@gmail.com
4         5 2018-03-15     West  Timothy           ncec1320@gmail.com
5         6 2018-04-01     East   Martha  alam.mdimtiyaz085@gmail.com
6         7 2018-04-18  Central   Martha  alam.mdimtiyaz085@gmail.com
7         8 2018-05-05  Central  Hermann        ishtiaz2023@gmail.com
8         9 2018-05-22     West  Douglas   hussainakbar7786@gmail.com
9        10 2018-06-08     East   Martha  alam.mdimtiyaz085@gmail.com
10       11 2018-06-25  Central  Hermann        ishtiaz2023@gmail.com
11       12 2018-07-12     East   Martha  alam.mdimtiyaz085@gmail.com
12       13 2018-07-29     East  Douglas   hussainakbar7786@gmail.com
13       14 2018-08-15     East   Martha  alam.mdimtiyaz085@gmail.com
14       15 2018-09-01  Central  Douglas   hussainakbar7786@gmail.com
15       16 2018-09-18     East   Martha  alam.mdimtiyaz085@gmail.com
16       17 2018-10-05  Central  Hermann        ishtiaz2023@gmail.com
17       18 2018-10-22     East   Martha  alam.mdimtiyaz085@gmail.com
18       19 2018-11-08     East  Douglas   hussainakbar7786@gmail.com
19       20 2018-11-25  Central  Hermann        ishtiaz2023@gmail.com
20       21 2018-12-12  Central  Douglas   hussainakbar7786@gmail.com
21       22 2018-12-29     East  Douglas   hussainakbar7786@gmail.com
22       23 2019-01-15  Central  Timothy           ncec1320@gmail.com
23       24 2019-02-01  Central  Douglas   hussainakbar7786@gmail.com
24       25 2019-02-18     East   Martha  alam.mdimtiyaz085@gmail.com
25       26 2019-03-07     West  Timothy           ncec1320@gmail.com
26       27 2019-03-24  Central  Hermann        ishtiaz2023@gmail.com
27       28 2019-04-10  Central   Martha  alam.mdimtiyaz085@gmail.com
28       29 2019-04-27     East   Martha  alam.mdimtiyaz085@gmail.com
29       30 2019-05-14  Central  Timothy           ncec1320@gmail.com
30       31 2019-05-31  Central  Timothy           ncec1320@gmail.com
31       32 2019-06-17  Central  Hermann        ishtiaz2023@gmail.com
32       33 2019-07-04     East   Martha  alam.mdimtiyaz085@gmail.com
33       34 2019-07-21  Central  Hermann        ishtiaz2023@gmail.com
34       35 2019-08-07  Central  Hermann        ishtiaz2023@gmail.com
35       36 2019-08-24     West  Timothy           ncec1320@gmail.com
36       37 2019-09-10  Central  Timothy           ncec1320@gmail.com
37       38 2019-09-27     West  Timothy           ncec1320@gmail.com
38       39 2019-10-14     West  Douglas   hussainakbar7786@gmail.com
39       40 2019-10-31  Central   Martha  alam.mdimtiyaz085@gmail.com
40       41 2014-12-20    North     Mark      farhanazam100@gmail.com
41       42 2014-12-20    North     Mark      farhanazam100@gmail.com

     SalesMan          Item  Units  Unit_price  Sale_amt
0   Alexander    Television     95      1198.0  113810.0
1      Shelli  Home Theater     50       400.0   20000.0
2        Luis    Television     36      1198.0   43128.0
3       David    Cell Phone     27       225.0    6075.0
4     Stephen    Television     56      1198.0   67088.0
5   Alexander  Home Theater     60       500.0   30000.0
6      Steven    Television     75      1198.0   89850.0
7        Luis    Television     90      1198.0  107820.0
8     Michael    Television     32      1198.0   38336.0
9   Alexander  Home Theater     60       500.0   30000.0
10      Sigal    Television     90      1198.0  107820.0
11      Diana  Home Theater     29       500.0   14500.0
12      Karen  Home Theater     81       500.0   40500.0
13  Alexander    Television     35      1198.0   41930.0
14       John          Desk      2       125.0     250.0
15  Alexander   Video Games     16        58.5     936.0
16      Sigal  Home Theater     28       500.0   14000.0
17  Alexander    Cell Phone     64       225.0   14400.0
18      Karen    Cell Phone     15       225.0    3375.0
19     Shelli   Video Games     96        58.5    5616.0
20       John    Television     67      1198.0   80266.0
21      Karen   Video Games     74        58.5    4329.0
22      David  Home Theater     46       500.0   23000.0
23       John  Home Theater     87       500.0   43500.0
24  Alexander  Home Theater      4       500.0    2000.0
25    Stephen  Home Theater      7       500.0    3500.0
26       Luis   Video Games     50        58.5    2925.0
27     Steven    Television     66      1198.0   79068.0
28      Diana    Cell Phone     96       225.0   21600.0
29      David    Television     53      1198.0   63494.0
30      David  Home Theater     80       500.0   40000.0
31     Shelli          Desk      5       125.0     625.0
32  Alexander   Video Games     62        58.5    3627.0
33      Sigal   Video Games     55        58.5    3217.5
34     Shelli   Video Games     42        58.5    2457.0
35    Stephen          Desk      3       125.0     375.0
36      David    Television      7      1198.0    8386.0
37    Stephen    Cell Phone     76       225.0   17100.0
38    Michael  Home Theater     57       500.0   28500.0
39     Steven    Television     14      1198.0   16772.0
40    Stephen      Earphone     10       245.0    2450.0
41    Stephen        Tablet     15      7600.0  114000.0

In [ ]:
import pandas as pd                     # Import PANDAS Library
df = pd.read_excel("Sales.xlsx")        # Read the excel file
display(df)                             # Show the data in table with format

,OrderID,OrderDate,Region,Manager,Man_Email_ID,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2018-01-06,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,95,1198.0,113810.0
1,2,2018-01-23,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Home Theater,50,400.0,20000.0
2,3,2018-02-09,Central,Hermann,ishtiaz2023@gmail.com,Luis,Television,36,1198.0,43128.0
3,4,2018-02-26,Central,Timothy,ncec1320@gmail.com,David,Cell Phone,27,225.0,6075.0
4,5,2018-03-15,West,Timothy,ncec1320@gmail.com,Stephen,Television,56,1198.0,67088.0
5,6,2018-04-01,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
6,7,2018-04-18,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,75,1198.0,89850.0
7,8,2018-05-05,Central,Hermann,ishtiaz2023@gmail.com,Luis,Television,90,1198.0,107820.0
8,9,2018-05-22,West,Douglas,hussainakbar7786@gmail.com,Michael,Television,32,1198.0,38336.0
9,10,2018-06-08,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
10,11,2018-06-25,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Television,90,1198.0,107820.0
11,12,2018-07-12,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Home Theater,29,500.0,14500.0
12,13,2018-07-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Home Theater,81,500.0,40500.0
13,14,2018-08-15,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,35,1198.0,41930.0
14,15,2018-09-01,Central,Douglas,hussainakbar7786@gmail.com,John,Desk,2,125.0,250.0
15,16,2018-09-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,16,58.5,936.0
16,17,2018-10-05,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Home Theater,28,500.0,14000.0
17,18,2018-10-22,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Cell Phone,64,225.0,14400.0
18,19,2018-11-08,East,Douglas,hussainakbar7786@gmail.com,Karen,Cell Phone,15,225.0,3375.0
19,20,2018-11-25,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Video Games,96,58.5,5616.0
20,21,2018-12-12,Central,Douglas,hussainakbar7786@gmail.com,John,Television,67,1198.0,80266.0
21,22,2018-12-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Video Games,74,58.5,4329.0
22,23,2019-01-15,Central,Timothy,ncec1320@gmail.com,David,Home Theater,46,500.0,23000.0
23,24,2019-02-01,Central,Douglas,hussainakbar7786@gmail.com,John,Home Theater,87,500.0,43500.0
24,25,2019-02-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,4,500.0,2000.0
25,26,2019-03-07,West,Timothy,ncec1320@gmail.com,Stephen,Home Theater,7,500.0,3500.0
26,27,2019-03-24,Central,Hermann,ishtiaz2023@gmail.com,Luis,Video Games,50,58.5,2925.0
27,28,2019-04-10,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,66,1198.0,79068.0
28,29,2019-04-27,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Cell Phone,96,225.0,21600.0
29,30,2019-05-14,Central,Timothy,ncec1320@gmail.com,David,Television,53,1198.0,63494.0
30,31,2019-05-31,Central,Timothy,ncec1320@gmail.com,David,Home Theater,80,500.0,40000.0
31,32,2019-06-17,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Desk,5,125.0,625.0
32,33,2019-07-04,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,62,58.5,3627.0
33,34,2019-07-21,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Video Games,55,58.5,3217.5
34,35,2019-08-07,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Video Games,42,58.5,2457.0
35,36,2019-08-24,West,Timothy,ncec1320@gmail.com,Stephen,Desk,3,125.0,375.0
36,37,2019-09-10,Central,Timothy,ncec1320@gmail.com,David,Television,7,1198.0,8386.0
37,38,2019-09-27,West,Timothy,ncec1320@gmail.com,Stephen,Cell Phone,76,225.0,17100.0
38,39,2019-10-14,West,Douglas,hussainakbar7786@gmail.com,Michael,Home Theater,57,500.0,28500.0
39,40,2019-10-31,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,14,1198.0,16772.0
40,41,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Earphone,10,245.0,2450.0
41,42,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Tablet,15,7600.0,114000.0

In [ ]:
import pandas as pd                     # Import PANDAS Library
df = pd.read_excel("Sales.xlsx")        # Read the excel file
df                                      # Show the data in table with format

,OrderID,OrderDate,Region,Manager,Man_Email_ID,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2018-01-06,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,95,1198.0,113810.0
1,2,2018-01-23,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Home Theater,50,400.0,20000.0
2,3,2018-02-09,Central,Hermann,ishtiaz2023@gmail.com,Luis,Television,36,1198.0,43128.0
3,4,2018-02-26,Central,Timothy,ncec1320@gmail.com,David,Cell Phone,27,225.0,6075.0
4,5,2018-03-15,West,Timothy,ncec1320@gmail.com,Stephen,Television,56,1198.0,67088.0
5,6,2018-04-01,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
6,7,2018-04-18,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,75,1198.0,89850.0
7,8,2018-05-05,Central,Hermann,ishtiaz2023@gmail.com,Luis,Television,90,1198.0,107820.0
8,9,2018-05-22,West,Douglas,hussainakbar7786@gmail.com,Michael,Television,32,1198.0,38336.0
9,10,2018-06-08,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
10,11,2018-06-25,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Television,90,1198.0,107820.0
11,12,2018-07-12,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Home Theater,29,500.0,14500.0
12,13,2018-07-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Home Theater,81,500.0,40500.0
13,14,2018-08-15,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,35,1198.0,41930.0
14,15,2018-09-01,Central,Douglas,hussainakbar7786@gmail.com,John,Desk,2,125.0,250.0
15,16,2018-09-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,16,58.5,936.0
16,17,2018-10-05,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Home Theater,28,500.0,14000.0
17,18,2018-10-22,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Cell Phone,64,225.0,14400.0
18,19,2018-11-08,East,Douglas,hussainakbar7786@gmail.com,Karen,Cell Phone,15,225.0,3375.0
19,20,2018-11-25,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Video Games,96,58.5,5616.0
20,21,2018-12-12,Central,Douglas,hussainakbar7786@gmail.com,John,Television,67,1198.0,80266.0
21,22,2018-12-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Video Games,74,58.5,4329.0
22,23,2019-01-15,Central,Timothy,ncec1320@gmail.com,David,Home Theater,46,500.0,23000.0
23,24,2019-02-01,Central,Douglas,hussainakbar7786@gmail.com,John,Home Theater,87,500.0,43500.0
24,25,2019-02-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,4,500.0,2000.0
25,26,2019-03-07,West,Timothy,ncec1320@gmail.com,Stephen,Home Theater,7,500.0,3500.0
26,27,2019-03-24,Central,Hermann,ishtiaz2023@gmail.com,Luis,Video Games,50,58.5,2925.0
27,28,2019-04-10,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,66,1198.0,79068.0
28,29,2019-04-27,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Cell Phone,96,225.0,21600.0
29,30,2019-05-14,Central,Timothy,ncec1320@gmail.com,David,Television,53,1198.0,63494.0
30,31,2019-05-31,Central,Timothy,ncec1320@gmail.com,David,Home Theater,80,500.0,40000.0
31,32,2019-06-17,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Desk,5,125.0,625.0
32,33,2019-07-04,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,62,58.5,3627.0
33,34,2019-07-21,Central,Hermann,ishtiaz2023@gmail.com,Sigal,Video Games,55,58.5,3217.5
34,35,2019-08-07,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Video Games,42,58.5,2457.0
35,36,2019-08-24,West,Timothy,ncec1320@gmail.com,Stephen,Desk,3,125.0,375.0
36,37,2019-09-10,Central,Timothy,ncec1320@gmail.com,David,Television,7,1198.0,8386.0
37,38,2019-09-27,West,Timothy,ncec1320@gmail.com,Stephen,Cell Phone,76,225.0,17100.0
38,39,2019-10-14,West,Douglas,hussainakbar7786@gmail.com,Michael,Home Theater,57,500.0,28500.0
39,40,2019-10-31,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,14,1198.0,16772.0
40,41,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Earphone,10,245.0,2450.0
41,42,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Tablet,15,7600.0,114000.0

In [ ]:
import pandas as pd                # Import Pandas Library
df = pd.read_excel("Sales.xlsx")   # Read the excel file
df.head()                          # head()-To show top 5 record

,OrderID,OrderDate,Region,Manager,Man_Email_ID,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2018-01-06,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,95,1198.0,113810.0
1,2,2018-01-23,Central,Hermann,ishtiaz2023@gmail.com,Shelli,Home Theater,50,400.0,20000.0
2,3,2018-02-09,Central,Hermann,ishtiaz2023@gmail.com,Luis,Television,36,1198.0,43128.0
3,4,2018-02-26,Central,Timothy,ncec1320@gmail.com,David,Cell Phone,27,225.0,6075.0
4,5,2018-03-15,West,Timothy,ncec1320@gmail.com,Stephen,Television,56,1198.0,67088.0

In [ ]:
import pandas as pd
df = pd.read_excel("Sales.xlsx")
df.tail()                         # tail() - To show bottom 5 records

,OrderID,OrderDate,Region,Manager,Man_Email_ID,SalesMan,Item,Units,Unit_price,Sale_amt
37,38,2019-09-27,West,Timothy,ncec1320@gmail.com,Stephen,Cell Phone,76,225.0,17100.0
38,39,2019-10-14,West,Douglas,hussainakbar7786@gmail.com,Michael,Home Theater,57,500.0,28500.0
39,40,2019-10-31,Central,Martha,alam.mdimtiyaz085@gmail.com,Steven,Television,14,1198.0,16772.0
40,41,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Earphone,10,245.0,2450.0
41,42,2014-12-20,North,Mark,farhanazam100@gmail.com,Stephen,Tablet,15,7600.0,114000.0

In [4]:
import pandas as pd                                          # Import Pandas Library
df = pd.read_excel("Sales.xlsx")                             # Read Excel File
sel_col = df[['OrderID', 'Region', 'Manager', 'Sale_amt']]   # To show desired Column
sel_col                                                      # Show all records

    OrderID   Region  Manager  Sale_amt
0         1     East   Martha  113810.0
1         2  Central  Hermann   20000.0
2         3  Central  Hermann   43128.0
3         4  Central  Timothy    6075.0
4         5     West  Timothy   67088.0
5         6     East   Martha   30000.0
6         7  Central   Martha   89850.0
7         8  Central  Hermann  107820.0
8         9     West  Douglas   38336.0
9        10     East   Martha   30000.0
10       11  Central  Hermann  107820.0
11       12     East   Martha   14500.0
12       13     East  Douglas   40500.0
13       14     East   Martha   41930.0
14       15  Central  Douglas     250.0
15       16     East   Martha     936.0
16       17  Central  Hermann   14000.0
17       18     East   Martha   14400.0
18       19     East  Douglas    3375.0
19       20  Central  Hermann    5616.0
20       21  Central  Douglas   80266.0
21       22     East  Douglas    4329.0
22       23  Central  Timothy   23000.0
23       24  Central  Douglas   43500.0
24       25     East   Martha    2000.0
25       26     West  Timothy    3500.0
26       27  Central  Hermann    2925.0
27       28  Central   Martha   79068.0
28       29     East   Martha   21600.0
29       30  Central  Timothy   63494.0
30       31  Central  Timothy   40000.0
31       32  Central  Hermann     625.0
32       33     East   Martha    3627.0
33       34  Central  Hermann    3217.5
34       35  Central  Hermann    2457.0
35       36     West  Timothy     375.0
36       37  Central  Timothy    8386.0
37       38     West  Timothy   17100.0
38       39     West  Douglas   28500.0
39       40  Central   Martha   16772.0
40       41    North     Mark    2450.0
41       42    North     Mark  114000.0

In [3]:
import pandas as pd                                          # Import Pandas Library
df = pd.read_excel("Sales.xlsx")                             # Read Excel File
sel_col = df[['OrderID', 'Region', 'Manager', 'Sale_amt']]   # To show desired Column
sel_col.head()                                               # Show the top 5 records

   OrderID   Region  Manager  Sale_amt
0        1     East   Martha  113810.0
1        2  Central  Hermann   20000.0
2        3  Central  Hermann   43128.0
3        4  Central  Timothy    6075.0
4        5     West  Timothy   67088.0

In [6]:
import pandas as pd
df = pd.read_excel("Sales.xlsx")
east_data = df[df["Region"] == "East"]        # To display the record with one condition
east_data

,OrderID,OrderDate,Region,Manager,Man_Email_ID,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2018-01-06,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,95,1198.0,113810.0
5,6,2018-04-01,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
9,10,2018-06-08,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,60,500.0,30000.0
11,12,2018-07-12,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Home Theater,29,500.0,14500.0
12,13,2018-07-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Home Theater,81,500.0,40500.0
13,14,2018-08-15,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Television,35,1198.0,41930.0
15,16,2018-09-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,16,58.5,936.0
17,18,2018-10-22,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Cell Phone,64,225.0,14400.0
18,19,2018-11-08,East,Douglas,hussainakbar7786@gmail.com,Karen,Cell Phone,15,225.0,3375.0
21,22,2018-12-29,East,Douglas,hussainakbar7786@gmail.com,Karen,Video Games,74,58.5,4329.0
24,25,2019-02-18,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Home Theater,4,500.0,2000.0
28,29,2019-04-27,East,Martha,alam.mdimtiyaz085@gmail.com,Diana,Cell Phone,96,225.0,21600.0
32,33,2019-07-04,East,Martha,alam.mdimtiyaz085@gmail.com,Alexander,Video Games,62,58.5,3627.0